name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
      - run: tar -xf zig-linux-x86_64-0.11.0.tar.xz
      - run: echo "$PWD/zig-linux-x86_64-0.11.0/zig" >> $GITHUB_PATH
      - run: zig build test
