name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      steps:
      - uses: actions/checkout@v3
      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz'
          name: 'zig'
          version: '0.11.0'
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: zig build test
