name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
      - run: tar -xf zig-linux-x86_64-0.11.0.tar.xz
      - run: export PATH=$PWD/zig-linux-x86_64-0.11.0:$PATH

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: zig build test
