name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          key: "zig-0.11.0"
          path: |
            zig-linux-x86_64-0.11.0
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz && tar -xf zig-linux-x86_64-0.11.0.tar.xz
      - run: echo "$PWD/zig-linux-x86_64-0.11.0" >> $GITHUB_PATH
      - run: zig build test
